version: "3.8"

services:
  api:
    build: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:3000
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - mongo

  bot:
    build: ./bot
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - "27018:27017"
  nginx:
    build: ./nginx
    ports:
      - "3001:3001"
      - "444:444"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - mynetwork
