version: "3.8"

services:
  api:
    build: ./api
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:3000
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - mongo
  bot:
    build: ./bot
    command: python bot.py
    networks:
      - mynetwork
    depends_on:
      - mongo
  mongo:
    image: mongo:6-jammy
    networks:
      - mynetwork
    ports:
      - "27018:27017"
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/data:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  mynetwork:
    driver: bridge
