version: "3.8"

services:
  api:
    build: ./api
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:3001
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    depends_on:
      - mongo

  bot:
    build: ./bot
    networks:
      - mynetwork
    depends_on:
      - api

  mongo:
    image: mongo:4.4
    networks:
      - mynetwork
    ports:
      - "27018:27017"
  nginx:
    build: ./nginx
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - mynetwork
    depends_on:
      - api
#  certbot:
#    container_name: service_certbot
#    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  mynetwork:
    driver: bridge
