version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  bot:
    build: ./bot
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - "27018:27017"
